"""Bilibili video download service using yt-dlp.

Only downloads a single P (page) — never the entire BV collection.
"""

import os
import re
import shutil
import subprocess
import sys
import logging

logger = logging.getLogger(__name__)


def find_ytdlp() -> list[str] | None:
    """Return yt-dlp command as a list (e.g. ['yt-dlp'] or ['python', '-m', 'yt_dlp']), or None."""
    if shutil.which("yt-dlp"):
        return ["yt-dlp"]
    # Fallback: use Python module (Windows where Scripts dir may not be in PATH)
    try:
        subprocess.run([sys.executable, "-m", "yt_dlp", "--version"], capture_output=True, timeout=15)
        return [sys.executable, "-m", "yt_dlp"]
    except Exception:
        return None


def parse_bilibili_url(url: str, page: int | None = None) -> str | None:
    """Parse a B站 URL and return the canonical video URL with ?p={page}.

    Handles:
        - https://www.bilibili.com/video/BVxxxx?p=5
        - https://www.bilibili.com/video/BVxxxx (adds ?p={page})
        - https://player.bilibili.com/player.html?bvid=BVxxxx&p=5
        - https://www.bilibili.com/video/BVxxxx/?spm_id_from=...&p=5

    Returns None if the URL cannot be parsed.
    """
    if not url:
        return None

    url = url.strip()

    # Case 1: player.bilibili.com iframe URL — extract bvid and p
    player_match = re.search(
        r'player\.bilibili\.com/player\.html\?.*bvid=([A-Za-z0-9]+)',
        url
    )
    if player_match:
        bvid = player_match.group(1)
        p_match = re.search(r'[&?]p=(\d+)', url)
        p = int(p_match.group(1)) if p_match else (page or 1)
        return f"https://www.bilibili.com/video/{bvid}?p={p}"

    # Case 2: Standard bilibili.com/video/BVxxxx URL
    bv_match = re.search(r'bilibili\.com/video/([A-Za-z0-9]+)', url)
    if bv_match:
        bvid = bv_match.group(1)
        p_match = re.search(r'[?&]p=(\d+)', url)
        p = int(p_match.group(1)) if p_match else (page or 1)
        return f"https://www.bilibili.com/video/{bvid}?p={p}"

    return None


def get_video_filename(task_id: int, course_id: int, lesson_id: int | None, page: int | None) -> str:
    """Return the expected video file path for a given task/lesson.

    Format: temp/video/c{course_id}_l{lesson_id}_p{page}_t{task_id}.mp4
    Using this naming avoids collisions across different lessons and re-runs.
    """
    return f"temp/video/c{course_id}_l{lesson_id or 0}_p{page or 1}_t{task_id}.mp4"


def find_existing_video(course_id: int, lesson_id: int | None, page: int | None) -> str | None:
    """Check if a video file already exists for this course/lesson/page combo.

    Returns the path of the first matching file, or None.
    """
    prefix = f"c{course_id}_l{lesson_id or 0}_p{page or 1}"
    video_dir = "temp/video"
    if not os.path.isdir(video_dir):
        return None
    for name in os.listdir(video_dir):
        if name.startswith(prefix) and name.endswith(".mp4"):
            path = os.path.join(video_dir, name)
            if os.path.getsize(path) > 0:
                return path
    return None


def _make_temp_cookie_file(cookie_string: str) -> str:
    """Convert a raw cookie string to a Netscape-format temp file for yt-dlp.

    Input: "SESSDATA=xxx; bili_jct=yyy; buvid3=zzz"
    Output: path to temp file in Netscape cookie format.
    """
    import tempfile
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, encoding="utf-8")
    tmp.write("# Netscape HTTP Cookie File\n")
    tmp.write("# Auto-generated by PyGrow from BILIBILI_COOKIE env var\n")
    tmp.write("\n")
    for part in cookie_string.split(";"):
        part = part.strip()
        if "=" not in part:
            continue
        key, _, value = part.partition("=")
        key = key.strip()
        value = value.strip()
        # Netscape format: domain  flag  path  secure  expires  name  value
        tmp.write(f".bilibili.com\tTRUE\t/\tTRUE\t0\t{key}\t{value}\n")
    tmp.close()
    return tmp.name


def _get_setting(name: str, default: str = "") -> str:
    """Read config value from Pydantic settings (which reads .env), fallback to os.environ."""
    try:
        from app.config import settings
        val = getattr(settings, name, None)
        if val:
            return val
    except Exception:
        pass
    return os.environ.get(name.upper(), default)


def _find_cookie_args(ytdlp: list[str]) -> list[str]:
    """Try to find working B站 cookies. Returns yt-dlp cookie args or empty list.

    Reads from Pydantic settings (BILIBILI_COOKIE / BILIBILI_COOKIE_FILE in .env).
    Falls back to browser cookies (edge/chrome/firefox) for local dev.
    """
    # 1) Raw cookie string from config
    cookie_string = _get_setting("bilibili_cookie")
    if cookie_string:
        try:
            tmp_path = _make_temp_cookie_file(cookie_string)
            logger.info("Using cookies from BILIBILI_COOKIE config")
            return ["--cookies", tmp_path]
        except Exception as e:
            logger.warning("Failed to create cookie file: %s", e)

    # 2) Cookie file path from config
    cookie_file = _get_setting("bilibili_cookie_file")
    if cookie_file:
        if not os.path.isabs(cookie_file):
            backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            cookie_file = os.path.join(backend_dir, cookie_file)
        logger.info("Looking for cookie file at: %s", cookie_file)
        if os.path.exists(cookie_file):
            logger.info("Using cookie file: %s", cookie_file)
            return ["--cookies", cookie_file]
        else:
            logger.warning("Cookie file NOT FOUND: %s", cookie_file)

    # 3) Browser cookies (local dev)
    for browser in ["edge", "chrome", "firefox", "chromium"]:
        try:
            result = subprocess.run(
                ytdlp + ["--cookies-from-browser", browser, "--print", "cookies", "https://www.bilibili.com"],
                capture_output=True, text=True, timeout=15,
            )
            if result.returncode == 0 and "buvid3" in result.stdout:
                logger.info("Using cookies from browser: %s", browser)
                return ["--cookies-from-browser", browser]
        except Exception:
            continue

    logger.warning("No B站 cookies found — 412 errors may occur.")
    return []


def download_bilibili_video(
    video_url: str,
    task_id: int,
    course_id: int,
    lesson_id: int | None = None,
    page: int | None = None,
    prefer_small: bool = True,
) -> str:
    """Download a single B站 video (one P only) using yt-dlp.

    Args:
        video_url: B站 video URL (canonical format with ?p=N).
        task_id: AI note task ID (for unique filename).
        course_id: Course ID.
        lesson_id: Lesson ID (optional).
        page: Page/P number of the B站 video.
        prefer_small: If True, download the smallest available format (faster).

    Returns:
        Path to the downloaded video file.

    Raises:
        RuntimeError: If yt-dlp is not installed, download fails, or URL is invalid.
    """
    ytdlp = find_ytdlp()
    if not ytdlp:
        raise RuntimeError("当前环境未安装 yt-dlp，请先执行 pip install yt-dlp")

    # Parse URL to ensure it points to a single P
    canonical = parse_bilibili_url(video_url, page)
    if not canonical:
        raise RuntimeError(f"无法解析B站视频链接: {video_url[:100]}")

    output_path = get_video_filename(task_id, course_id, lesson_id, page)

    # Check if already downloaded for this lesson
    existing = find_existing_video(course_id, lesson_id, page)
    if existing and os.path.getsize(existing) > 0:
        logger.info("Reusing existing video: %s", existing)
        if existing != output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            shutil.copy2(existing, output_path)
        return output_path

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    cookie_args = _find_cookie_args(ytdlp)

    # yt-dlp command: single video only, no playlist/collection
    # B站 uses separate video+audio streams — always use bestvideo+bestaudio merge
    fmt = "bestvideo[height<=720]+bestaudio/bestvideo+bestaudio/best[height<=720]"
    if prefer_small:
        fmt = "worstvideo[height<=480]+worstaudio/worstvideo+worstaudio/best[height<=480]"

    cmd = ytdlp + [
        "--no-playlist",
        "-f", fmt,
        "-o", output_path,
        "--merge-output-format", "mp4",
        "--no-part",
        "--no-mtime",
        "--add-header", "Referer:https://www.bilibili.com",
        "--add-header", "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    ] + cookie_args + [
        canonical,
    ]

    logger.info("Running yt-dlp: %s", " ".join(cmd))

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)

    if result.returncode != 0:
        stderr = result.stderr.strip() or result.stdout.strip() or "unknown error"
        logger.error("yt-dlp failed: %s", stderr)
        extra = ""
        if "412" in stderr and not cookie_args:
            extra = "\n提示：B站要求登录Cookie，请在Chrome中登录B站后重试，或设置 BILIBILI_COOKIE_FILE 环境变量指向cookies.txt"
        raise RuntimeError(f"视频下载失败: {stderr[-500:]}{extra}")

    # Verify the file exists
    if not os.path.exists(output_path) or os.path.getsize(output_path) == 0:
        raise RuntimeError("下载完成但未生成有效视频文件")

    logger.info("Video downloaded: %s (%.1f MB)", output_path, os.path.getsize(output_path) / 1024 / 1024)
    return output_path


def get_video_duration(filepath: str) -> float:
    """Get video duration in seconds using ffprobe."""
    import subprocess
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", filepath],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0 and result.stdout.strip():
            return float(result.stdout.strip())
    except (subprocess.TimeoutExpired, ValueError, OSError) as e:
        logger.warning("Failed to get video duration: %s", e)
    return 0.0


def cleanup_temp_files(task_id: int):
    """Delete temporary video and audio files for a completed task.

    Keeps the database records (transcript + AI notes are in the DB).
    """
    video_dir = "temp/video"
    audio_dir = "temp/audio"
    pattern = f"_t{task_id}."

    for base_dir in [video_dir, audio_dir]:
        if not os.path.isdir(base_dir):
            continue
        for name in os.listdir(base_dir):
            if pattern in name:
                path = os.path.join(base_dir, name)
                try:
                    os.remove(path)
                    logger.info("Cleaned up: %s", path)
                except OSError as e:
                    logger.warning("Failed to cleanup %s: %s", path, e)
